version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: payzone-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payroll_db
      MYSQL_USER: payroll_user
      MYSQL_PASSWORD: payroll_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/seeds/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - payzone-network

  # PHP Backend (API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payzone-backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: payroll_db
      DB_USERNAME: payroll_user
      DB_PASSWORD: payroll_pass
      JWT_SECRET: supersecretkeyforjwttokens123456789
      APP_ENV: production
      APP_DEBUG: false
    ports:
      - "8000:9000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    networks:
      - payzone-network
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'OK';"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:alpine
    container_name: payzone-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend:/var/www/html
    depends_on:
      - backend
    networks:
      - payzone-network

  # Redis (Optional - for caching)
  redis:
    image: redis:7-alpine
    container_name: payzone-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - payzone-network

  # Adminer (Database Management)
  adminer:
    image: adminer
    container_name: payzone-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - payzone-network

volumes:
  db_data:
  redis_data:

networks:
  payzone-network:
    driver: bridge